# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
    
# ignore all warnings from all pods
inhibit_all_warnings!

# Pods for Widget

target 'Widget' do
    pod 'Alamofire', '~> 4.7'
    	pod 'ObjectMapper', '~> 3.0'
    	pod 'AlamofireObjectMapper', '~> 5.0'
    	pod 'SwiftyJSON', '~> 3.1'
    	pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
end